AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - test/**/*_test.rb

Layout/LineLength:
  Max: 120
